# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd9e0e0c1a169afd3aa564e165bc5c1e82f038c18d19be582387122574c4479f4c31567e8bbcbe3523aa392a4016cf3d198bca9609bad6e0cae26272b875b954

test:
  secret_key_base: 55e2702faf6361ba443c89a6c236768fb7d64418c1b38e31e949b7259be35554424bfe68e766563472bd109475790eedf45a3e5cce8d0efbb939033fb0035888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
